### ISSUE TITLE
Use intent instead of camera

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-shopping-list#19]
By using an intent that accesses a camera app, the camera permission can be saved

**Comment by Ifill-Brito** [comment]
The first implementation was done by using an intent, but we had the problem that the camera app could not save the photo inside of the shopping list app and the shopping list app could not read the URL given by the camera app because of not having the external storage permission. So there was no way (meaning we didn't find a way, maybe there is one) to pass the photo to the shopping list app. The thumbnail can be passed through the intent, but the real images are too big and therefore only the URL can be passed.

We had to make a decision between Camera and External Storage Permission.

**Comment by Yonjuni** [comment]
Okay, thanks for explaining.
